[build]
  base = "ai-ticketing-system/frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://ai-ticketing-system-1-t7wn.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
